apiVersion: v1
kind: Secret
metadata:
  name: secret-pccore
type: Opaque
data:
  ClientId: 
  ClientSecret: 
  EventLoggerCosmosMongoDBConnectionString: 
  MongoHost: 
  MongoUsername: 
  MongoPassword: 
  EtcdHost: ZXRjZC1jbGllbnQK
  EtcdPort: MjM3OQo=
  ExecutionFrequencyInMinutes: MzAK
  ServiceBusConnectionString: 
  TenantId: 
