FROM microsoft/dotnet:2.2-sdk

# install VS Remote Debugger
RUN apt-get update
#RUN apt-get install zip unzip curl -y
#RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg

#setup ssh for remote debug
#COPY Informer/MandateServiceInformer/ssh/ssh_config /etc/ssh/
RUN apt-get install -y --no-install-recommends openssh-server
RUN mkdir /var/run/sshd
RUN echo "root:root" | chpasswd
COPY Informer/MandateServiceInformer/ssh/sshd_config /etc/ssh/
#RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
#RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]