#affects individual containers that doesn't have ResourceLimit
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-pc-dev
  namespace: pc
spec:
  limits:
    - default:
        cpu: 250m
        memory: 128Mi
      defaultRequest:
        cpu: 250m
        memory: 128Mi
      max:
        cpu: 750m
        memory: 500Mi
      min:
        cpu: 50m
        memory: 50Mi
